/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/availability": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Текущие настройки доступности */
        get: operations["AvailabilityRoutes_getAvailability"];
        /**
         * @description Полная замена настроек доступности.
         *     Интервалы каждого правила должны быть кратны 15 минутам и не пересекаться в рамках дня.
         */
        put: operations["AvailabilityRoutes_updateAvailability"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Владелец смотрит список предстоящих встреч (только активные, от текущего момента) */
        get: operations["OwnerBookingRoutes_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bookings/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** @description Владелец отменяет встречу (перевод в статус cancelled, слот снова свободен) */
        delete: operations["OwnerBookingRoutes_cancel"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/event-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Список своих типов событий */
        get: operations["OwnerEventTypeRoutes_list"];
        put?: never;
        /** @description Создать тип события */
        post: operations["OwnerEventTypeRoutes_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/event-types/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** @description Обновить тип события */
        put: operations["OwnerEventTypeRoutes_update"];
        post?: never;
        /** @description Удалить тип события (если нет активных будущих броней) */
        delete: operations["OwnerEventTypeRoutes_remove"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/owners": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Регистрация нового владельца календаря.
         *     При успехе устанавливается сессионная cookie (как при входе).
         *     409 — email или slug уже заняты.
         */
        post: operations["OwnerRoutes_register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/public/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Публичный профиль владельца для страницы /u/{slug} */
        get: operations["PublicRoutes_getOwner"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/public/{slug}/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Гость создаёт бронирование на свободный слот владельца.
         *     409 — слот занят (пересечение с другой бронью), в прошлом, вне расписания
         *     или дальше горизонта бронирования (14 дней).
         */
        post: operations["PublicRoutes_createBooking"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/public/{slug}/event-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Типы событий этого владельца */
        get: operations["PublicRoutes_listEventTypes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/public/{slug}/slots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Свободные слоты за период [from, to] для выбранного типа события.
         *     Длина слота = durationMinutes типа. Горизонт — 14 дней включая сегодня.
         *     Даты from/to интерпретируются в таймзоне владельца.
         */
        get: operations["PublicRoutes_listSlots"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Текущая сессия (проверка «я залогинен?») */
        get: operations["SessionRoutes_current"];
        put?: never;
        /** @description Вход владельца. Устанавливает сессионную cookie. */
        post: operations["SessionRoutes_login"];
        /** @description Выход владельца. Удаляет сессию. */
        delete: operations["SessionRoutes_logout"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description 409 — email или slug уже заняты при регистрации */
        AlreadyExistsError: {
            /** @enum {string} */
            code: "already_exists";
            message: string;
        };
        /**
         * @description Настройки доступности владельца: часовой пояс + набор недельных правил
         * @example {
         *       "timezone": "Europe/Moscow",
         *       "rules": [
         *         {
         *           "weekday": 1,
         *           "startTime": "10:00",
         *           "endTime": "18:00"
         *         },
         *         {
         *           "weekday": 3,
         *           "startTime": "10:00",
         *           "endTime": "14:00"
         *         }
         *       ]
         *     }
         */
        Availability: {
            /** @description Часовой пояс владельца, IANA-идентификатор (например, Europe/Moscow) */
            timezone: string;
            rules: components["schemas"]["AvailabilityRule"][];
        };
        /**
         * @description Правило доступности: повторяющийся недельный интервал,
         *     в котором владелец готов принимать звонки (например, Пн 10:00–18:00).
         */
        AvailabilityRule: {
            /**
             * Format: int32
             * @description День недели по ISO 8601: 1 — понедельник … 7 — воскресенье
             */
            weekday: number;
            /** @description Начало интервала, локальное время владельца в формате HH:MM */
            startTime: string;
            /** @description Конец интервала, локальное время владельца в формате HH:MM */
            endTime: string;
        };
        /**
         * @description Бронирование: гость занял конкретный слот под конкретный тип события
         * @example {
         *       "id": 1,
         *       "eventTypeId": 1,
         *       "startsAt": "2026-07-27T10:00:00Z",
         *       "endsAt": "2026-07-27T10:30:00Z",
         *       "guestName": "Иван Петров",
         *       "guestEmail": "ivan@example.com",
         *       "comment": "Хочу обсудить проект",
         *       "status": "active",
         *       "createdAt": "2026-07-21T12:00:00Z"
         *     }
         */
        Booking: {
            /** Format: int32 */
            id: number;
            /** Format: int32 */
            eventTypeId: number;
            /** Format: date-time */
            startsAt: string;
            /** Format: date-time */
            endsAt: string;
            guestName: string;
            /** Format: email */
            guestEmail: string;
            /** @description Комментарий гостя владельцу (тема звонка и т. п.) */
            comment?: string;
            status: components["schemas"]["BookingStatus"];
            /** Format: date-time */
            createdAt: string;
        };
        /** @description Данные для создания бронирования гостем */
        BookingCreate: {
            /** Format: int32 */
            eventTypeId: number;
            /**
             * Format: date-time
             * @description Начало выбранного слота, UTC. Должно совпадать со слотом из GET …/slots.
             */
            startsAt: string;
            guestName: string;
            /** Format: email */
            guestEmail: string;
            comment?: string;
        };
        /** @enum {string} */
        BookingStatus: "active" | "cancelled";
        /** @description 409 — конфликт: слот уже занят или находится в прошлом */
        ConflictError: {
            /** @enum {string} */
            code: "slot_unavailable";
            message: string;
        };
        /**
         * @description Тип события — то, на что гость записывается (например, «Вводный звонок»)
         * @example {
         *       "id": 1,
         *       "name": "Вводный звонок",
         *       "description": "Знакомство и обсуждение задачи",
         *       "durationMinutes": 30
         *     }
         */
        EventType: {
            /** Format: int32 */
            id: number;
            name: string;
            description?: string;
            /**
             * Format: int32
             * @description Длительность встречи в минутах: 15–240, кратно 15.
             *     От неё зависят длина слота и шаг сетки при вычислении свободного времени.
             */
            durationMinutes: number;
        };
        /** @description Создание / обновление типа события владельцем */
        EventTypeWrite: {
            name: string;
            description?: string;
            /** Format: int32 */
            durationMinutes: number;
        };
        /** @description Ошибка одного поля при валидации */
        FieldError: {
            field: string;
            message: string;
        };
        /** @description 404 — ресурс не найден */
        NotFoundError: {
            /** @enum {string} */
            code: "not_found";
            message: string;
        };
        /**
         * @description Владелец календаря. Создаётся через регистрацию; публичная страница —
         *     /u/{slug} на фронтенде и /api/public/{slug} в API.
         * @example {
         *       "id": 1,
         *       "name": "Кирилл Чистов",
         *       "email": "owner@example.com",
         *       "slug": "kirill"
         *     }
         */
        Owner: {
            /** Format: int32 */
            id: number;
            /** @description Отображаемое имя, показывается гостю на странице бронирования */
            name: string;
            /** Format: email */
            email: string;
            /**
             * @description Публичный идентификатор в URL: латиница, цифры, дефис;
             *     2–32 символа, начинается и заканчивается буквой или цифрой.
             */
            slug: string;
        };
        /** @description Данные регистрации нового владельца */
        OwnerCreate: {
            name: string;
            /** Format: email */
            email: string;
            password: string;
            slug: string;
        };
        /**
         * @description Публичный профиль владельца для гостевой страницы бронирования
         * @example {
         *       "id": 1,
         *       "name": "Кирилл Чистов",
         *       "slug": "kirill",
         *       "timezone": "Europe/Moscow"
         *     }
         */
        OwnerPublic: {
            /** Format: int32 */
            id: number;
            name: string;
            slug: string;
            /** @description IANA-таймзона владельца (в ней заданы правила доступности) */
            timezone: string;
        };
        /** @description Активная сессия */
        Session: {
            owner: components["schemas"]["Owner"];
        };
        /** @description Учётные данные владельца для входа */
        SessionCreate: {
            /** Format: email */
            email: string;
            password: string;
        };
        /**
         * @description Свободный слот. Вычисляется на лету из правил доступности и длительности
         *     выбранного типа события за вычетом активных бронирований — в базе не хранится.
         * @example {
         *       "startsAt": "2026-07-27T10:00:00Z",
         *       "endsAt": "2026-07-27T10:30:00Z"
         *     }
         */
        Slot: {
            /**
             * Format: date-time
             * @description Начало слота, UTC
             */
            startsAt: string;
            /**
             * Format: date-time
             * @description Конец слота, UTC (startsAt + durationMinutes типа события)
             */
            endsAt: string;
        };
        /** @description 401 — нет активной сессии владельца или неверные учётные данные */
        UnauthorizedError: {
            /** @enum {string} */
            code: "unauthorized";
            message: string;
        };
        /** @description 422 — ошибка валидации входных данных */
        ValidationError: {
            /** @enum {string} */
            code: "validation_error";
            message: string;
            errors?: components["schemas"]["FieldError"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AvailabilityRoutes_getAvailability: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Availability"];
                };
            };
            /** @description 401 — нет активной сессии владельца или неверные учётные данные */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnauthorizedError"];
                };
            };
        };
    };
    AvailabilityRoutes_updateAvailability: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Availability"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Availability"];
                };
            };
            /** @description 401 — нет активной сессии владельца или неверные учётные данные */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnauthorizedError"];
                };
            };
            /** @description 422 — ошибка валидации входных данных */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationError"];
                };
            };
        };
    };
    OwnerBookingRoutes_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Booking"][];
                };
            };
            /** @description 401 — нет активной сессии владельца или неверные учётные данные */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnauthorizedError"];
                };
            };
        };
    };
    OwnerBookingRoutes_cancel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description There is no content to send for this request, but the headers may be useful. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 401 — нет активной сессии владельца или неверные учётные данные */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnauthorizedError"];
                };
            };
            /** @description 404 — ресурс не найден */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundError"];
                };
            };
        };
    };
    OwnerEventTypeRoutes_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventType"][];
                };
            };
            /** @description 401 — нет активной сессии владельца или неверные учётные данные */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnauthorizedError"];
                };
            };
        };
    };
    OwnerEventTypeRoutes_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EventTypeWrite"];
            };
        };
        responses: {
            /** @description The request has succeeded and a new resource has been created as a result. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventType"];
                };
            };
            /** @description 401 — нет активной сессии владельца или неверные учётные данные */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnauthorizedError"];
                };
            };
            /** @description 422 — ошибка валидации входных данных */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationError"];
                };
            };
        };
    };
    OwnerEventTypeRoutes_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EventTypeWrite"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventType"];
                };
            };
            /** @description 401 — нет активной сессии владельца или неверные учётные данные */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnauthorizedError"];
                };
            };
            /** @description 404 — ресурс не найден */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundError"];
                };
            };
            /** @description 422 — ошибка валидации входных данных */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationError"];
                };
            };
        };
    };
    OwnerEventTypeRoutes_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description There is no content to send for this request, but the headers may be useful. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 401 — нет активной сессии владельца или неверные учётные данные */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnauthorizedError"];
                };
            };
            /** @description 404 — ресурс не найден */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundError"];
                };
            };
            /** @description 422 — ошибка валидации входных данных */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationError"];
                };
            };
        };
    };
    OwnerRoutes_register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OwnerCreate"];
            };
        };
        responses: {
            /** @description The request has succeeded and a new resource has been created as a result. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
            /** @description 409 — email или slug уже заняты при регистрации */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlreadyExistsError"];
                };
            };
            /** @description 422 — ошибка валидации входных данных */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationError"];
                };
            };
        };
    };
    PublicRoutes_getOwner: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OwnerPublic"];
                };
            };
            /** @description 404 — ресурс не найден */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundError"];
                };
            };
        };
    };
    PublicRoutes_createBooking: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BookingCreate"];
            };
        };
        responses: {
            /** @description The request has succeeded and a new resource has been created as a result. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Booking"];
                };
            };
            /** @description 404 — ресурс не найден */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundError"];
                };
            };
            /** @description 409 — конфликт: слот уже занят или находится в прошлом */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConflictError"];
                };
            };
            /** @description 422 — ошибка валидации входных данных */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationError"];
                };
            };
        };
    };
    PublicRoutes_listEventTypes: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventType"][];
                };
            };
            /** @description 404 — ресурс не найден */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundError"];
                };
            };
        };
    };
    PublicRoutes_listSlots: {
        parameters: {
            query: {
                /** @description Тип события: определяет длительность слота */
                eventTypeId: number;
                /** @description Начало периода, YYYY-MM-DD */
                from: string;
                /** @description Конец периода, YYYY-MM-DD */
                to: string;
            };
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Slot"][];
                };
            };
            /** @description 404 — ресурс не найден */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundError"];
                };
            };
            /** @description 422 — ошибка валидации входных данных */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationError"];
                };
            };
        };
    };
    SessionRoutes_current: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
            /** @description 401 — нет активной сессии владельца или неверные учётные данные */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnauthorizedError"];
                };
            };
        };
    };
    SessionRoutes_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SessionCreate"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
            /** @description 401 — нет активной сессии владельца или неверные учётные данные */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnauthorizedError"];
                };
            };
            /** @description 422 — ошибка валидации входных данных */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationError"];
                };
            };
        };
    };
    SessionRoutes_logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description There is no content to send for this request, but the headers may be useful. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
